name: Folder Indexing

on:
  workflow_call:
     inputs:
      go-version:
        description: "Go version"
        required: false
        type: string

permissions:
  contents: write  # Required for auto-committing

jobs:
  index-folders:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.go-version }}

      - name: Download Go Dependencies
        run: |
          cd indexer
          go mod tidy

      - name: Build Indexer
        run: |
          cd indexer
          go build -o ../indexer .

      - name: Run Indexer
        run: ./indexer/indexer --dirname ./samples

      - name: Commit Indexed Files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git diff --cached --quiet || git commit -m "Auto-index folders"
          git push
