name: Folder Indexing

on:
  workflow_call:
     inputs:
       samples:
         description: 'Path to the samples directory'
         required: false
         type: string

permissions:
  contents: write  # Required for auto-committing

jobs:
  index-folders:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Download prebuilt indexer binary
        run: |
          curl -L -o indexer https://github.com/smaudd/leafcutter/releases/download/v1.0.0/indexer-linux-amd64
          chmod +x indexer

      - name: Run Indexer
        run: ./indexer --dirname ./samples

      - name: Commit Indexed Files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git diff --cached --quiet || git commit -m "Auto-index folders"
          git push
